#!/bin/bash
prj="code_the_web"
src="https://github.com/amekusa/code_the_web"
dst="$HOME/Desktop/${prj}_$(date +%Y)"
if [ -e "$dst" ]; then
	echo "//// ERROR //// The destination: $dst already exists."
	exit 1
fi
xcode-select --install
if ! git clone "$src" "$dst"; then
	echo "//// ERROR //// git clone failed."
	exit 1
fi
if [ ! -d "$dst" ]; then
	echo "//// ERROR //// $dst is not found after git-clone. There must be something wrong here..."
	exit 1
fi
echo
echo "---- SUCCESS ----"
echo "src: $src"
echo "dst: $dst"
echo "================="
echo
